remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: GitHub Pages + trackswitch.js
description: [This page shows how to use trackswitch.js with GitHub pages]

markdown: kramdown

output:
  html_document:
    includes:
       in_header: header.html